### ISSUE TITLE
Moonraker wont start after install

### ISSUE THREAD

**Issue by JustKilian** [mainsail-crew/moonraker-timelapse#103]
After i installed moonraker-timelapse and rebooted, I was greeted by a 502 Bad Gateway error. I promptly tried to fix this through the stated solutions on various moonraker forums and wasnt successfull. I even reinstalled moonraker-timelapse. 

[moonraker.log](https://github.com/mainsail-crew/moonraker-timelapse/files/10879374/moonraker.log)

This is the logfile. I really dont know whats happening.

**Comment by FrYakaTKoP** [comment]
````Mar 03 07:37:09 fluiddpi python[545]: [shell_command.py:_check_proc_success()] - Command (git -C /home/pi/Klipper-Adaptive-Meshing-Purging fetch origin --prune --progress) exited with return code 128
Mar 03 07:37:10 fluiddpi python[545]: [git_deploy.py:initialize()] - Git Repo Klipper-Adaptive-Meshing-Purging: Initialization failure
Mar 03 07:37:10 fluiddpi python[545]: Traceback (most recent call last):
Mar 03 07:37:10 fluiddpi python[545]:   File "/home/pi/moonraker/moonraker/components/update_manager/git_deploy.py", line 347, in initialize
Mar 03 07:37:10 fluiddpi python[545]:     await self.fetch()
Mar 03 07:37:10 fluiddpi python[545]:   File "/home/pi/moonraker/moonraker/components/update_manager/git_deploy.py", line 648, in fetch
Mar 03 07:37:10 fluiddpi python[545]:     await self._run_git_cmd_async(
Mar 03 07:37:10 fluiddpi python[545]:   File "/home/pi/moonraker/moonraker/components/update_manager/git_deploy.py", line 940, in _run_git_cmd_async
Mar 03 07:37:10 fluiddpi python[545]:     raise self.server.error(f"Git Command '{cmd}' failed")
Mar 03 07:37:10 fluiddpi python[545]: utils.ServerError: Git Command 'fetch origin --prune --progress' failed
Mar 03 07:37:10 fluiddpi python[545]: [git_deploy.py:refresh()] - Error Refreshing git state
Mar 03 07:37:10 fluiddpi python[545]: Traceback (most recent call last):
Mar 03 07:37:10 fluiddpi python[545]:   File "/home/pi/moonraker/moonraker/components/update_manager/git_deploy.py", line 53, in refresh
Mar 03 07:37:10 fluiddpi python[545]:     await self._update_repo_state()
Mar 03 07:37:10 fluiddpi python[545]:   File "/home/pi/moonraker/moonraker/components/update_manager/git_deploy.py", line 59, in _update_repo_state
Mar 03 07:37:10 fluiddpi python[545]:     await self.repo.initialize(need_fetch=need_fetch)
Mar 03 07:37:10 fluiddpi python[545]:   File "/home/pi/moonraker/moonraker/components/update_manager/git_deploy.py", line 347, in initialize
Mar 03 07:37:10 fluiddpi python[545]:     await self.fetch()
Mar 03 07:37:10 fluiddpi python[545]:   File "/home/pi/moonraker/moonraker/components/update_manager/git_deploy.py", line 648, in fetch
Mar 03 07:37:10 fluiddpi python[545]:     await self._run_git_cmd_async(
Mar 03 07:37:10 fluiddpi python[545]:   File "/home/pi/moonraker/moonraker/components/update_manager/git_deploy.py", line 940, in _run_git_cmd_async
Mar 03 07:37:10 fluiddpi python[545]:     raise self.server.error(f"Git Command '{cmd}' failed")
Mar 03 07:37:10 fluiddpi python[545]: utils.ServerError: Git Command 'fetch origin --prune --progress' failed```

Looks like you have a problem with `Klipper-Adaptive-Meshing-Purging` not with timelapse. Timelapse seems to initialise just fine. On the otherhand it weird that it fails in `git_deploy.py` you may have error in your moonraker.conf in the update section related to the meshing purging plugin

Please close this issue, if you can't provide a log where timelapse is failing to initialise
