### ISSUE TITLE
Timelaps not rendering

### ISSUE THREAD

**Issue by miklas206** [mainsail-crew/moonraker-timelapse#135]
So i have an error where i cannot render my timelapse its just stuck with this like the picture i have tried to search the web for help but could not find anything.....

![Skærmbillede 2023-10-05 132812](https://github.com/mainsail-crew/moonraker-timelapse/assets/72841842/1d95f284-5b56-42ad-a194-d045b5e16710)

**Comment by LeoMGames** [comment]
I have the same problem. My workaround is to download the images and use this tool. https://timelapsetool.com/

**Comment by kjkent** [comment]
Yep I have this issue too -- the timelapse successfully rendered exactly 10 times, then hasn't worked since. grepping through the logs shows `timelapse.py:render() is already running` a bunch of times, and this persists across reboots & restarts of the systemd services.

Interestingly, the last successful render kicked out this error message that I missed at the time because the video did render:

```log
./moonraker.log.2024-01-21:2024-01-21 21:51:16,278 [timelapse.py:render()] - start FFMPEG: /usr/bin/ffmpeg -r 30 -i '/tmp/timelapse/printer/frame%6d.jpg' -threads 2 -g 5 -crf 17 -vcodec libx264 -pix_fmt yuv420p -an  '/tmp/timelapse/printer/timelapse_CE3S1_galile0's_Label_Slot_Bin_1x2x6_Gridfinity.gcode_20240121_2151.mp4' -y
./moonraker.log.2024-01-21:2024-01-21 21:51:16,279 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f3a48897b10>>, <Task finished name='Task-560220' coro=<Timelapse.render() done, defined at /home/kjkent/moonraker/moonraker/components/timelapse.py:598> exception=ValueError('No closing quotation')>)
./moonraker.log.2024-01-21-Traceback (most recent call last):
./moonraker.log.2024-01-21-  File "/home/kjkent/moonraker-env/lib/python3.11/site-packages/tornado/ioloop.py", line 750, in _run_callback
./moonraker.log.2024-01-21-    ret = callback()
./moonraker.log.2024-01-21-          ^^^^^^^^^^
./moonraker.log.2024-01-21-  File "/home/kjkent/moonraker-env/lib/python3.11/site-packages/tornado/ioloop.py", line 774, in _discard_future_result
./moonraker.log.2024-01-21-    future.result()
./moonraker.log.2024-01-21:  File "/home/kjkent/moonraker/moonraker/components/timelapse.py", line 711, in render
./moonraker.log.2024-01-21-    scmd = shell_cmd.build_shell_command(cmd, self.ffmpeg_cb)
./moonraker.log.2024-01-21-           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
./moonraker.log.2024-01-21-  File "/home/kjkent/moonraker/moonraker/components/shell_command.py", line 368, in build_shell_command
```

**Edit:** I deleted my gcodes and it's now rendering again, perhaps the single `'` in a gcode filename is causing `render()` to persistently fail?

**Comment by aredington** [comment]
I got bit by this, I believe it may originate at https://github.com/mainsail-crew/moonraker-timelapse/blob/main/component/timelapse.py#L630 where the filename of the originating gcode is interpolated.

The filename I printed when I got bit was "joe's-synth-stand.gcode" and problem is related to the filename including a single tick character.

**Comment by elijalukas** [comment]
anybody found a solution? i have the same issue and no special file name.
