### ISSUE TITLE
utils.ServerError: Key '3e61d605-e206-4f6c-8a30-bbccecc5a9b5' in namespace 'webcams' not found

### ISSUE THREAD

**Issue by sreichholf** [mainsail-crew/moonraker-timelapse#41]
I had this error on my klipper/mainsail/timelapse installation today.

```
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/components/database.py", line 221, in get_item
    ns = self._get_record(namespace, key_list[0])
  File "/home/pi/moonraker/moonraker/components/database.py", line 322, in _get_record
    f"Key '{key}' in namespace '{namespace}' not found", 404)
utils.ServerError: Key '3e61d605-e206-4f6c-8a30-bbccecc5a9b5' in namespace 'webcams' not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/moonraker.py", line 239, in load_component
    component = load_func(config)
  File "/home/pi/moonraker/moonraker/components/timelapse.py", line 793, in load_component
    return Timelapse(config)
  File "/home/pi/moonraker/moonraker/components/timelapse.py", line 123, in __init__
    webcamconfig = self.webcams_db[self.config['camera']]
  File "/home/pi/moonraker/moonraker/components/database.py", line 478, in __getitem__
    return self.get(key, default=SENTINEL)
  File "/home/pi/moonraker/moonraker/components/database.py", line 467, in get
    return self.db.get_item(self.namespace, key, default)
  File "/home/pi/moonraker/moonraker/components/database.py", line 227, in get_item
    f"Key '{key}' in namespace '{namespace}' not found", 404)
utils.ServerError: Key '3e61d605-e206-4f6c-8a30-bbccecc5a9b5' in namespace 'webcams' not found
```

I worked around it with the following change in timelapse.py
```
diff --git a/component/timelapse.py b/component/timelapse.py
index 91724cc..97840f1 100644
--- a/component/timelapse.py
+++ b/component/timelapse.py
@@ -119,7 +119,7 @@ class Timelapse:
         self.overwriteDbconfigWithConfighelper()

         # Read Webcam config from Database
-        if not self.config['camera'] == '':
+        if self.config['camera'] and self.config['camera'] in self.webcams_db.keys():
             webcamconfig = self.webcams_db[self.config['camera']]
             if isinstance(webcamconfig, asyncio.Future):
                 self.getwebcamconfig(webcamconfig.result())
```

This was really just quick & dirty and I have no Idea if it's the right way to fix this.
I would guess that a "dissapearing" camera probably shouldn't happen.

There have been no changes to my cams, only klipper/mainsail/mooraker/timelapse updates yesterday (iirc).

**Comment by FrYakaTKoP** [comment]
the commit [2b877ef](https://github.com/mainsail-crew/moonraker-timelapse/commit/2b877ef6fbf2e13d03efd09eab6a857905c62b0a) should resolve this issue
